"""initial migration

Revision ID: 3e4603249fad
Revises: 
Create Date: 2026-09-03 17:36:27.031594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4603249fad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('day_number', sa.Integer(), nullable=False))
    op.add_column('itineraries', sa.Column('itinerary_data', sa.String(length=500), nullable=False))
    op.drop_column('itineraries', 'end_time')
    op.drop_column('itineraries', 'activity')
    op.drop_column('itineraries', 'location')
    op.drop_column('itineraries', 'start_time')
    op.drop_column('itineraries', 'day')
    op.add_column('places', sa.Column('place_longitude', sa.Float(), nullable=False))
    op.add_column('places', sa.Column('place_latitude', sa.Float(), nullable=False))
    op.drop_column('places', 'place_address')
    op.drop_column('places', 'place_description')
    op.drop_constraint(op.f('preferences_user_id_fkey'), 'preferences', type_='foreignkey')
    op.drop_column('preferences', 'user_id')
    op.drop_column('preferences', 'preference_value')
    op.add_column('trips', sa.Column('starting_destination', sa.String(length=100), nullable=False))
    op.add_column('trips', sa.Column('ending_destination', sa.String(length=100), nullable=False))
    op.add_column('trips', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['user_id'])
    op.drop_column('trips', 'destination')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.add_column('trips', sa.Column('destination', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'status')
    op.drop_column('trips', 'ending_destination')
    op.drop_column('trips', 'starting_destination')
    op.add_column('preferences', sa.Column('preference_value', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('preferences', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('preferences_user_id_fkey'), 'preferences', 'users', ['user_id'], ['user_id'])
    op.add_column('places', sa.Column('place_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('places', sa.Column('place_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('places', 'place_latitude')
    op.drop_column('places', 'place_longitude')
    op.add_column('itineraries', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('itineraries', sa.Column('start_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('itineraries', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('itineraries', sa.Column('activity', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('itineraries', sa.Column('end_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('itineraries', 'itinerary_data')
    op.drop_column('itineraries', 'day_number')
    # ### end Alembic commands ###
